name: Molk

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Molk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [13.x]

    steps:
      - name: Request github action api.
        run: |
          curl -X POST https://api.github.com/repos/Torther/blogFramework/dispatches \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{secrets.ACTIONS_TRIGGER_TOKEN}}" \
              --data '{"event_type": "Hexo"}'
