name: Molk

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Molk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [13.x]

    steps:
      # - name: Start post notification.
      #   run: |
      #     curl https://qmsg.zendee.cn/send/${{secrets.QMSG_KEY}} -X POST -d 'msg=发现有文章更新，准备部署cayzlh.com '

      - name: Request github action api.
        run: |
          curl -X POST https://api.github.com/repos/cayzlh/blog-framework/dispatches \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{secrets.ACTIONS_TRIGGER_TOKEN}}" \
              --data '{"event_type": "Hexo"}'

      # - name: End post notification.
      #   run: |
      #     curl https://qmsg.zendee.cn/send/${{secrets.QMSG_KEY}} -X POST -d 'msg=正在发送webhook请求GitHub Action... '
